parse_html.activity._parse_html_activity: fix regression in bs4 >= 4.13.0
previously it resulted in
`TypeError: _parse_html_activity.<locals>.soup_filter() missing 1 required positional argument: 'data'`

Seems like it has to do some `SoupStrainer` changes menioned for 4.13 release in https://git.launchpad.net/beautifulsoup/tree/CHANGELOG

The fixed version works on 4.12 too, so backwards compatible

In addtition to the test in previous commit, checked against all my takeouts, parses the same results